<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Therapeute extends \App\Entity\Therapeute implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'approche' => [parent::class, 'approche', null, 16],
        "\0".parent::class."\0".'cadreProfessionnel' => [parent::class, 'cadreProfessionnel', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'infoPratiques' => [parent::class, 'infoPratiques', null, 16],
        "\0".parent::class."\0".'messageContacts' => [parent::class, 'messageContacts', null, 16],
        "\0".parent::class."\0".'motifConsultations' => [parent::class, 'motifConsultations', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'pages' => [parent::class, 'pages', null, 16],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null, 16],
        "\0".parent::class."\0".'presentation' => [parent::class, 'presentation', null, 16],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null, 16],
        'approche' => [parent::class, 'approche', null, 16],
        'cadreProfessionnel' => [parent::class, 'cadreProfessionnel', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'infoPratiques' => [parent::class, 'infoPratiques', null, 16],
        'messageContacts' => [parent::class, 'messageContacts', null, 16],
        'motifConsultations' => [parent::class, 'motifConsultations', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'pages' => [parent::class, 'pages', null, 16],
        'prenom' => [parent::class, 'prenom', null, 16],
        'presentation' => [parent::class, 'presentation', null, 16],
        'telephone' => [parent::class, 'telephone', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
