<?php

namespace ContainerEDKmHOZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F5ow9REService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.f5ow9RE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.f5ow9RE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\InfoPratiqueRepository', 'getInfoPratiqueRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\InfoPratiqueRepository',
        ]);
    }
}
