<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEDKmHOZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEDKmHOZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEDKmHOZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEDKmHOZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEDKmHOZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'EDKmHOZ',
    'container.build_id' => '7c4f40a5',
    'container.build_time' => 1778068448,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEDKmHOZ');
